#############################################################################
# Makefile for building: ntt
# Generated by qmake (3.1) (Qt 5.9.5)
# Project:  ntt.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile ntt.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -pipe -O2 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++1y -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../mylibrary/tmxlite/tmxlite -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ntt1.0.0
DISTDIR = /home/ngothoitrung/mario-reamke-c-/.tmp/ntt1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -L/home/ngothoitrung/mario-reamke-c-/../mylibrary/tmxlite/tmxlite/ -ltmxlite -lsfml-graphics -lsfml-window -lsfml-audio -lsfml-system 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = animatedtile.cpp \
		animation.cpp \
		base.cpp \
		basegame.cpp \
		block.cpp \
		breakblockparticle.cpp \
		brickblock.cpp \
		buzzybeetle.cpp \
		camera.cpp \
		coin.cpp \
		enemy.cpp \
		firesplash.cpp \
		flower.cpp \
		framerate.cpp \
		gameobject.cpp \
		gamestate.cpp \
		goomba.cpp \
		item.cpp \
		koopa.cpp \
		main.cpp \
		mainstate.cpp \
		mariogame.cpp \
		marioworld.cpp \
		mushroom.cpp \
		node.cpp \
		particle.cpp \
		pickup.cpp \
		piranhaplant.cpp \
		player.cpp \
		playerfireball.cpp \
		property.cpp \
		questionblock.cpp \
		shineparticle.cpp \
		soundmanager.cpp \
		stage.cpp \
		statemanager.cpp \
		staticblock.cpp \
		statictile.cpp \
		texturemanager.cpp \
		tile.cpp \
		tiledmap.cpp \
		tileset.cpp \
		tilesets.cpp \
		timer.cpp \
		utils.cpp \
		platform.cpp \
		objectgroup.cpp \
		decorator.cpp \
		onewayplatform.cpp \
		jumper.cpp \
		portal.cpp \
		fontmanager.cpp 
OBJECTS       = animatedtile.o \
		animation.o \
		base.o \
		basegame.o \
		block.o \
		breakblockparticle.o \
		brickblock.o \
		buzzybeetle.o \
		camera.o \
		coin.o \
		enemy.o \
		firesplash.o \
		flower.o \
		framerate.o \
		gameobject.o \
		gamestate.o \
		goomba.o \
		item.o \
		koopa.o \
		main.o \
		mainstate.o \
		mariogame.o \
		marioworld.o \
		mushroom.o \
		node.o \
		particle.o \
		pickup.o \
		piranhaplant.o \
		player.o \
		playerfireball.o \
		property.o \
		questionblock.o \
		shineparticle.o \
		soundmanager.o \
		stage.o \
		statemanager.o \
		staticblock.o \
		statictile.o \
		texturemanager.o \
		tile.o \
		tiledmap.o \
		tileset.o \
		tilesets.o \
		timer.o \
		utils.o \
		platform.o \
		objectgroup.o \
		decorator.o \
		onewayplatform.o \
		jumper.o \
		portal.o \
		fontmanager.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/link_pkgconfig.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		ntt.pro animatedtile.h \
		animation.h \
		base.h \
		basegame.h \
		block.h \
		breakblockparticle.h \
		brickblock.h \
		buzzybeetle.h \
		camera.h \
		coin.h \
		enemy.h \
		firesplash.h \
		flower.h \
		framerate.h \
		gameobject.h \
		gamestate.h \
		goomba.h \
		item.h \
		keybinding.h \
		koopa.h \
		mainstate.h \
		mariogame.h \
		marioworld.h \
		mushroom.h \
		node.h \
		particle.h \
		pickup.h \
		piranhaplant.h \
		player.h \
		playerfireball.h \
		property.h \
		questionblock.h \
		shineparticle.h \
		soundmanager.h \
		stage.h \
		statemanager.h \
		staticblock.h \
		statictile.h \
		texturemanager.h \
		tile.h \
		tiledmap.h \
		tileset.h \
		tilesets.h \
		timer.h \
		utils.h \
		platform.h \
		objectgroup.h \
		decorator.h \
		onewayplatform.h \
		jumper.h \
		portal.h \
		fontmanager.h animatedtile.cpp \
		animation.cpp \
		base.cpp \
		basegame.cpp \
		block.cpp \
		breakblockparticle.cpp \
		brickblock.cpp \
		buzzybeetle.cpp \
		camera.cpp \
		coin.cpp \
		enemy.cpp \
		firesplash.cpp \
		flower.cpp \
		framerate.cpp \
		gameobject.cpp \
		gamestate.cpp \
		goomba.cpp \
		item.cpp \
		koopa.cpp \
		main.cpp \
		mainstate.cpp \
		mariogame.cpp \
		marioworld.cpp \
		mushroom.cpp \
		node.cpp \
		particle.cpp \
		pickup.cpp \
		piranhaplant.cpp \
		player.cpp \
		playerfireball.cpp \
		property.cpp \
		questionblock.cpp \
		shineparticle.cpp \
		soundmanager.cpp \
		stage.cpp \
		statemanager.cpp \
		staticblock.cpp \
		statictile.cpp \
		texturemanager.cpp \
		tile.cpp \
		tiledmap.cpp \
		tileset.cpp \
		tilesets.cpp \
		timer.cpp \
		utils.cpp \
		platform.cpp \
		objectgroup.cpp \
		decorator.cpp \
		onewayplatform.cpp \
		jumper.cpp \
		portal.cpp \
		fontmanager.cpp
QMAKE_TARGET  = ntt
DESTDIR       = 
TARGET        = ntt


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ntt.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/link_pkgconfig.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		ntt.pro
	$(QMAKE) -o Makefile ntt.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/link_pkgconfig.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
ntt.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile ntt.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

benchmark: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

animatedtile.o: animatedtile.cpp animatedtile.h \
		tile.h \
		property.h \
		base.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o animatedtile.o animatedtile.cpp

animation.o: animation.cpp animation.h \
		base.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o animation.o animation.cpp

base.o: base.cpp base.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o base.o base.cpp

basegame.o: basegame.cpp basegame.h \
		framerate.h \
		base.h \
		property.h \
		gamestate.h \
		statemanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o basegame.o basegame.cpp

block.o: block.cpp block.h \
		property.h \
		base.h \
		tile.h \
		marioworld.h \
		stage.h \
		camera.h \
		tiledmap.h \
		node.h \
		tilesets.h \
		tileset.h \
		enemy.h \
		gameobject.h \
		utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o block.o block.cpp

breakblockparticle.o: breakblockparticle.cpp breakblockparticle.h \
		particle.h \
		node.h \
		base.h \
		timer.h \
		animation.h \
		texturemanager.h \
		utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o breakblockparticle.o breakblockparticle.cpp

brickblock.o: brickblock.cpp brickblock.h \
		block.h \
		property.h \
		base.h \
		player.h \
		gameobject.h \
		node.h \
		utils.h \
		timer.h \
		animation.h \
		soundmanager.h \
		tile.h \
		breakblockparticle.h \
		particle.h \
		tiledmap.h \
		stage.h \
		camera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o brickblock.o brickblock.cpp

buzzybeetle.o: buzzybeetle.cpp buzzybeetle.h \
		enemy.h \
		gameobject.h \
		node.h \
		base.h \
		utils.h \
		property.h \
		texturemanager.h \
		soundmanager.h \
		animation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o buzzybeetle.o buzzybeetle.cpp

camera.o: camera.cpp camera.h \
		base.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o camera.o camera.cpp

coin.o: coin.cpp coin.h \
		pickup.h \
		gameobject.h \
		node.h \
		base.h \
		utils.h \
		property.h \
		animation.h \
		timer.h \
		soundmanager.h \
		texturemanager.h \
		stage.h \
		camera.h \
		shineparticle.h \
		particle.h \
		marioworld.h \
		tiledmap.h \
		tilesets.h \
		tileset.h \
		tile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o coin.o coin.cpp

enemy.o: enemy.cpp enemy.h \
		gameobject.h \
		node.h \
		base.h \
		utils.h \
		property.h \
		marioworld.h \
		stage.h \
		camera.h \
		tiledmap.h \
		tilesets.h \
		tileset.h \
		tile.h \
		block.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o enemy.o enemy.cpp

firesplash.o: firesplash.cpp firesplash.h \
		particle.h \
		node.h \
		base.h \
		timer.h \
		animation.h \
		texturemanager.h \
		utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o firesplash.o firesplash.cpp

flower.o: flower.cpp flower.h \
		pickup.h \
		gameobject.h \
		node.h \
		base.h \
		utils.h \
		property.h \
		texturemanager.h \
		soundmanager.h \
		player.h \
		timer.h \
		animation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o flower.o flower.cpp

framerate.o: framerate.cpp framerate.h \
		base.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o framerate.o framerate.cpp

gameobject.o: gameobject.cpp gameobject.h \
		node.h \
		base.h \
		utils.h \
		property.h \
		fontmanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gameobject.o gameobject.cpp

gamestate.o: gamestate.cpp gamestate.h \
		base.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gamestate.o gamestate.cpp

goomba.o: goomba.cpp goomba.h \
		enemy.h \
		gameobject.h \
		node.h \
		base.h \
		utils.h \
		property.h \
		animation.h \
		timer.h \
		texturemanager.h \
		mariogame.h \
		basegame.h \
		framerate.h \
		player.h \
		marioworld.h \
		stage.h \
		camera.h \
		tiledmap.h \
		tilesets.h \
		tileset.h \
		tile.h \
		soundmanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o goomba.o goomba.cpp

item.o: item.cpp item.h \
		gameobject.h \
		node.h \
		base.h \
		utils.h \
		property.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o item.o item.cpp

koopa.o: koopa.cpp koopa.h \
		enemy.h \
		gameobject.h \
		node.h \
		base.h \
		utils.h \
		property.h \
		timer.h \
		animation.h \
		marioworld.h \
		stage.h \
		camera.h \
		tiledmap.h \
		tilesets.h \
		tileset.h \
		tile.h \
		texturemanager.h \
		player.h \
		soundmanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o koopa.o koopa.cpp

main.o: main.cpp mariogame.h \
		basegame.h \
		framerate.h \
		base.h \
		property.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainstate.o: mainstate.cpp mainstate.h \
		gamestate.h \
		base.h \
		mariogame.h \
		basegame.h \
		framerate.h \
		property.h \
		marioworld.h \
		stage.h \
		camera.h \
		tiledmap.h \
		node.h \
		tilesets.h \
		tileset.h \
		tile.h \
		utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainstate.o mainstate.cpp

mariogame.o: mariogame.cpp mariogame.h \
		basegame.h \
		framerate.h \
		base.h \
		property.h \
		mainstate.h \
		gamestate.h \
		statemanager.h \
		texturemanager.h \
		utils.h \
		soundmanager.h \
		player.h \
		gameobject.h \
		node.h \
		timer.h \
		animation.h \
		fontmanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mariogame.o mariogame.cpp

marioworld.o: marioworld.cpp marioworld.h \
		stage.h \
		camera.h \
		base.h \
		tiledmap.h \
		node.h \
		tilesets.h \
		tileset.h \
		tile.h \
		property.h \
		mariogame.h \
		basegame.h \
		framerate.h \
		mainstate.h \
		gamestate.h \
		particle.h \
		timer.h \
		questionblock.h \
		soundmanager.h \
		block.h \
		brickblock.h \
		staticblock.h \
		animatedtile.h \
		statictile.h \
		player.h \
		gameobject.h \
		utils.h \
		animation.h \
		goomba.h \
		enemy.h \
		koopa.h \
		piranhaplant.h \
		texturemanager.h \
		coin.h \
		pickup.h \
		onewayplatform.h \
		platform.h \
		item.h \
		jumper.h \
		portal.h \
		objectgroup.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o marioworld.o marioworld.cpp

mushroom.o: mushroom.cpp mushroom.h \
		pickup.h \
		gameobject.h \
		node.h \
		base.h \
		utils.h \
		property.h \
		texturemanager.h \
		soundmanager.h \
		timer.h \
		player.h \
		animation.h \
		tiledmap.h \
		marioworld.h \
		stage.h \
		camera.h \
		tilesets.h \
		tileset.h \
		tile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mushroom.o mushroom.cpp

node.o: node.cpp node.h \
		base.h \
		stage.h \
		camera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o node.o node.cpp

particle.o: particle.cpp particle.h \
		node.h \
		base.h \
		timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o particle.o particle.cpp

pickup.o: pickup.cpp pickup.h \
		gameobject.h \
		node.h \
		base.h \
		utils.h \
		property.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pickup.o pickup.cpp

piranhaplant.o: piranhaplant.cpp piranhaplant.h \
		texturemanager.h \
		base.h \
		enemy.h \
		gameobject.h \
		node.h \
		utils.h \
		property.h \
		animation.h \
		timer.h \
		player.h \
		marioworld.h \
		stage.h \
		camera.h \
		tiledmap.h \
		tilesets.h \
		tileset.h \
		tile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o piranhaplant.o piranhaplant.cpp

player.o: player.cpp player.h \
		gameobject.h \
		node.h \
		base.h \
		utils.h \
		property.h \
		timer.h \
		animation.h \
		mainstate.h \
		gamestate.h \
		marioworld.h \
		stage.h \
		camera.h \
		tiledmap.h \
		tilesets.h \
		tileset.h \
		tile.h \
		texturemanager.h \
		mariogame.h \
		basegame.h \
		framerate.h \
		keybinding.h \
		enemy.h \
		block.h \
		soundmanager.h \
		playerfireball.h \
		pickup.h \
		item.h \
		platform.h \
		portal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o player.o player.cpp

playerfireball.o: playerfireball.cpp playerfireball.h \
		gameobject.h \
		node.h \
		base.h \
		utils.h \
		property.h \
		animation.h \
		timer.h \
		tiledmap.h \
		texturemanager.h \
		marioworld.h \
		stage.h \
		camera.h \
		tilesets.h \
		tileset.h \
		tile.h \
		enemy.h \
		firesplash.h \
		particle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o playerfireball.o playerfireball.cpp

property.o: property.cpp property.h \
		base.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o property.o property.cpp

questionblock.o: questionblock.cpp questionblock.h \
		soundmanager.h \
		base.h \
		block.h \
		property.h \
		tiledmap.h \
		node.h \
		marioworld.h \
		stage.h \
		camera.h \
		tilesets.h \
		tileset.h \
		tile.h \
		shineparticle.h \
		particle.h \
		timer.h \
		animation.h \
		utils.h \
		coin.h \
		pickup.h \
		gameobject.h \
		mushroom.h \
		texturemanager.h \
		player.h \
		flower.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o questionblock.o questionblock.cpp

shineparticle.o: shineparticle.cpp shineparticle.h \
		particle.h \
		node.h \
		base.h \
		timer.h \
		animation.h \
		texturemanager.h \
		utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o shineparticle.o shineparticle.cpp

soundmanager.o: soundmanager.cpp soundmanager.h \
		base.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o soundmanager.o soundmanager.cpp

stage.o: stage.cpp stage.h \
		camera.h \
		base.h \
		node.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stage.o stage.cpp

statemanager.o: statemanager.cpp statemanager.h \
		gamestate.h \
		base.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o statemanager.o statemanager.cpp

staticblock.o: staticblock.cpp staticblock.h \
		block.h \
		property.h \
		base.h \
		tile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o staticblock.o staticblock.cpp

statictile.o: statictile.cpp statictile.h \
		tile.h \
		property.h \
		base.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o statictile.o statictile.cpp

texturemanager.o: texturemanager.cpp texturemanager.h \
		base.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o texturemanager.o texturemanager.cpp

tile.o: tile.cpp tile.h \
		property.h \
		base.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tile.o tile.cpp

tiledmap.o: tiledmap.cpp tiledmap.h \
		node.h \
		base.h \
		block.h \
		property.h \
		marioworld.h \
		stage.h \
		camera.h \
		tilesets.h \
		tileset.h \
		tile.h \
		animatedtile.h \
		gameobject.h \
		utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tiledmap.o tiledmap.cpp

tileset.o: tileset.cpp tileset.h \
		tile.h \
		property.h \
		base.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tileset.o tileset.cpp

tilesets.o: tilesets.cpp tilesets.h \
		tileset.h \
		tile.h \
		property.h \
		base.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tilesets.o tilesets.cpp

timer.o: timer.cpp timer.h \
		base.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o timer.o timer.cpp

utils.o: utils.cpp utils.h \
		base.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o utils.o utils.cpp

platform.o: platform.cpp platform.h \
		item.h \
		gameobject.h \
		node.h \
		base.h \
		utils.h \
		property.h \
		animation.h \
		texturemanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o platform.o platform.cpp

objectgroup.o: objectgroup.cpp objectgroup.h \
		node.h \
		base.h \
		marioworld.h \
		stage.h \
		camera.h \
		tiledmap.h \
		tilesets.h \
		tileset.h \
		tile.h \
		property.h \
		player.h \
		gameobject.h \
		utils.h \
		timer.h \
		animation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objectgroup.o objectgroup.cpp

decorator.o: decorator.cpp decorator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o decorator.o decorator.cpp

onewayplatform.o: onewayplatform.cpp onewayplatform.h \
		platform.h \
		item.h \
		gameobject.h \
		node.h \
		base.h \
		utils.h \
		property.h \
		animation.h \
		player.h \
		timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o onewayplatform.o onewayplatform.cpp

jumper.o: jumper.cpp jumper.h \
		item.h \
		gameobject.h \
		node.h \
		base.h \
		utils.h \
		property.h \
		animation.h \
		timer.h \
		texturemanager.h \
		player.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o jumper.o jumper.cpp

portal.o: portal.cpp portal.h \
		gameobject.h \
		node.h \
		base.h \
		utils.h \
		property.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o portal.o portal.cpp

fontmanager.o: fontmanager.cpp fontmanager.h \
		base.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fontmanager.o fontmanager.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

